
PROCEDURE foxJson_Parse
LPARAMETERS cjson
IF VARTYPE(CJSON) <> "C"
   ERROR 11
   RETURN
ENDIF
LOCAL cobj,vretvalue
cobj = JSON_PARSE(CJSON)
IF NOT INLIST(JSON_TYPE(COBJ),4,5)
   vretvalue = JSON_VALUE(COBJ)
   JSON_DELETE(VRETVALUE)
   RETURN VRETVALUE
ENDIF
vretvalue = NEWOBJECT("collection")
FOXJSON_PARSE_ENUM(VRETVALUE,COBJ)
JSON_DELETE(COBJ)
RETURN VRETVALUE

PROCEDURE foxJson_Parse_Enum
LPARAMETERS oret,cobj
LOCAL x,ncount,nthistype
LOCAL otmpobj
nthistype = JSON_TYPE(COBJ)
ncount = JSON_CHILDS(COBJ)
FOR x = 1 TO NCOUNT
   IF INLIST(JSON_TYPE(COBJ,X),4,5)
      otmpobj = NEWOBJECT("collection")
      IF NTHISTYPE = 4
         ORET.ADD(OTMPOBJ,JSON_KEY(COBJ,X))
      ELSE
         ORET.ADD(OTMPOBJ)
      ENDIF
      FOXJSON_PARSE_ENUM(OTMPOBJ,JSON_VALUE(COBJ,X))
      LOOP
   ENDIF
   IF NTHISTYPE = 4
      ORET.ADD(JSON_VALUE(COBJ,X),JSON_KEY(COBJ,X))
   ELSE
      ORET.ADD(JSON_VALUE(COBJ,X))
   ENDIF
ENDFOR
