
DEFINE CLASS QiyuLog AS Custom


FUNCTION log
LPARAMETERS cmsg,cfilename
IF EMPTY(CFILENAME)
   cfilename = DTOC(DATE())+".txt"
ENDIF
cmsg = TTOC(DATETIME())+" "+CMSG+CHR(13)+CHR(10)
STRTOFILE(CMSG,CFILENAME,1)
ENDFUNC

ENDDEFINE
